{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "new-api.fullname" . }}-secret
  labels:
    {{- include "new-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.sessionSecret }}
  SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.sqlDsn }}
  SQL_DSN: {{ .Values.secrets.sqlDsn | quote }}
  {{- end }}
  {{- if .Values.secrets.redisConnString }}
  REDIS_CONN_STRING: {{ .Values.secrets.redisConnString | quote }}
  {{- end }}
{{- end }}
